kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: nameSpace
  name: experimentName
spec:
  selector:
    namespaces:
      - nameSpace
    labelSelectors:
      app: podName
  mode: all
  action: delay
  duration: time
  delay:
    latency: Latency
    correlation: 'Correlation'
    jitter: 0ms
  direction: to
