kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: nameSpace
  name: experimentName
spec:
  selector:
    namespaces:
      - nameSpace
    labelSelectors:
      app: podName
  mode: all
  action: duplicate
  duration: time
  duplicate:
    duplicate: 'Duplicate'
    correlation: 'Correlation'
  direction: to
