kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: nameSpace
  name: experimentName
spec:
  selector:
    namespaces:
      - nameSpace
    labelSelectors:
      app: podName
  mode: all
  stressors:
    memory:
      workers: memoryworker
      size: memorysize
    cpu:
      workers: cpuworker
      load: cpuload
  duration: time
