kind: TimeChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: nameSpace
  name: experimentName
spec:
  selector:
    namespaces:
      - nameSpace
    labelSelectors:
      app: podName
  mode: all
  timeOffset: 'TimeOffSet'
  clockIds:
    - CLOCK_REALTIME
  duration: Duration
